name: CMake CI
            
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
    # - name: ssh config
    #   run: |
    #     mkdir ~/.ssh
    #     touch ~/.ssh/config
    #     echo "Host png.github.com
    #                 HostName github.com" >> ~/.ssh/config
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: update submodules
      run: |
        git submodule update --init --recursive
    - name: installing more depens
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libprotobuf-dev protobuf-compiler ninja-build
        cd /home/runner/work/raw/raw/sub/gns
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        mkdir /home/runner/work/raw/raw/lib
        cp src/libGameNetworkingSockets_s.a /home/runner/work/raw/raw/lib/libGameNetworkingSockets.a #static
        cp bin/libGameNetworkingSockets.so /home/runner/work/raw/raw/lib/libGameNetworkingSockets.so #shared
        export LD_LIBRARY_PATH=/home/runner/work/raw/raw/lib:$LD_LIBRARY_PATH
        sudo ldconfig
    - name: installing vulkan sdk
      run: |
        mkdir /home/runner/vulk
        cd /home/runner/vulk
        wget -q -O - https://sdk.lunarg.com/sdk/download/1.3.296.0/linux/vulkansdk-linux-x86_64-1.3.296.0.tar.xz | tar -xJ -C .
        export VULKAN_SDK=/home/runner/vulk/1.3.296.0/x86_64
        export PATH=$VULKAN_SDK/bin:$PATH
        export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
        export VK_ICD_FILENAMES=$VULKAN_SDK/etc/vulkan/icd.d
        export VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/explicit_layer.d
        #sudo echo VULKAN_SDK=/home/runner/vulk/1.3.296.0/x86_64 >> /etc/environment
        #sudo echo PATH=$VULKAN_SDK/bin:$PATH >> /etc/environment
        #sudo echo LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH >> /etc/environment
        #sudo echo VK_ICD_FILENAMES=$VULKAN_SDK/etc/vulkan/icd.d >> /etc/environment
        #sudo echo VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/explicit_layer.d >> /etc/environment
        # echo "export VULKAN_SDK=/home/runner/vulk/1.3.296.0/x86_64" >> /home/runner/.bashrc
        # echo "export PATH=$VULKAN_SDK/bin:$PATH" >> /home/runner/.bashrc
        # echo "export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH" >> /home/runner/.bashrc
        # echo "export VK_ICD_FILENAMES=$VULKAN_SDK/etc/vulkan/icd.d" >> /home/runner/.bashrc
        # echo "export VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/explicit_layer.d" >> /home/runner/.bashrc
        echo VULKAN_SDK=/home/runner/vulk/1.3.296.0/x86_64 >> $GITHUB_ENV
        echo PATH=$VULKAN_SDK/bin:$PATH >> $GITHUB_ENV
        echo LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH >> $GITHUB_ENV
        echo VK_ICD_FILENAMES=$VULKAN_SDK/etc/vulkan/icd.d >> $GITHUB_ENV
        echo VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/explicit_layer.d >> $GITHUB_ENV
        sudo ldconfig
        # echo $PATH
    - name: vulkan_ci
      uses: NcStudios/VulkanCI@v1.1
    - name: verifying vulkan
      run: |
        #ls /home/runner/vulk/1.3.296.0/x86_64/bin/
        cp /home/runner/vulk/1.3.296.0/x86_64/bin/glslc $VULKAN_SDK/bin
        # echo $PATH
        # source /home/runner/.bashrc
        # echo $PATH
        $VULKAN_SDK/bin/glslc --version
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    # - name: Configure CMake
    #   run: >
    #     cmake -B ${{ steps.strings.outputs.build-output-dir }}
    #     -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
    #     -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
    #     -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    #     -G Ninja
    #     -S ${{ github.workspace }}

    # - name: Build
    #   run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    # - name: Test
    #   working-directory: ${{ steps.strings.outputs.build-output-dir }}
    #   run: ctest --build-config ${{ matrix.build_type }}
